name: Node.js CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:

        runs-on: ubuntu-20.04

        strategy:
            matrix:
                node-version: [ 12.x ]

        steps:
            -   uses: actions/checkout@v2
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node-version }}
            #            -   run: npm ci    # use instead of install if we choose to commit the `package-lock.json`
            -   run: npm install
            -   run: npm run build --if-present
    #            -   run: npm test
    #                env:
    #                    CI: true

    codefmt:
        runs-on: ubuntu-20.04
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    # Make sure the actual branch is checked out when running on pull requests
                    ref: ${{ github.head_ref }}

            -   name: Prettify code
                uses: creyD/prettier_action@v3.1
                with:
                    dry: true
                    prettier_options: --config wave/.prettierrc.json --ignore-path wave/.prettierignore --check wave/.
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
