name: Node.js CI

on:
    pull_request:
    merge_group:

jobs:
    build:

        runs-on: ubuntu-22.04

        strategy:
            matrix:
                node-version: [ 16.13.x, 18.10.x ] # Include version 18 once upgraded to Angular 15
                app: [ gis, dashboards/gfbio, dashboards/data-atlas, dashboards/nfdi-gdo, dashboards/ebv-analyzer ]

        steps:
            -   uses: actions/checkout@v3
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v3
                with:
                    node-version: ${{ matrix.node-version }}
                    cache: 'npm' # can be used only with a lockfile
            -   run: npm ci
            -   name: Build core
                run: npm run build-prod:core
            -   name: Build app ${{ matrix.app }}
                run: npm run build-prod:${{ matrix.app }}
            -   run: npm test
                env:
                    CI: true

    codestyle:
        name: Code Format and Lints
        runs-on: ubuntu-22.04
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
            -   name: Install Dependencies
                run: npm ci
            -   name: Code Format Check with Prettier
                run: npm run prettier -- --check .
            -   name: Check with Linter
                run: npm run lint
